version: '3.7'
services:

    db:
        image: aprismatic/prismadb-postgres:latest
        container_name: prismadb_postgres_db
        deploy:
            restart_policy:
                condition: any
        networks:
            - prismadb
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "Qwer!234"

    proxy:
        image: aprismatic.azurecr.io/prismadb-proxy-postgres:alpine
        container_name: prismadb_postgres_proxy
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ${PWD}/dbsettings.json:/dbsettings.json
        networks:
            - prismadb
        ports:
            - 4000:4000
        depends_on:
            - db
        environment:
            ListenPort: "4000"
            ServerAddress: "db"
            ServerPort: "5432"
            Database: "testdb"
            AdminUserId: "postgres"
            DatabaseSettings: /dbsettings.json

networks:
    prismadb: