version: '3.7'
services:

    db:
        image: aprismatic/prismadb-mysql:latest
        container_name: prismadb_mysql_db
        deploy:
            restart_policy:
                condition: any
        networks:
            - prismadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "Qwer!234"

    proxy:
        image: aprismatic.azurecr.io/prismadb-proxy-mysql:alpine
        container_name: prismadb_mysql_proxy
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ${PWD}/dbsettings.json:/dbsettings.json
        networks:
            - prismadb
        ports:
            - 4000:4000
        depends_on:
            - db
        environment:
            ListenPort: "4000"
            ServerAddress: "db"
            ServerPort: "3306"
            Database: "testdb"
            AdminUserId: "root"
            DatabaseSettings: /dbsettings.json

networks:
    prismadb: