version: '3.7'
services:

    db:
        image: aprismatic/prismadb-mysql:latest
        container_name: prismadb_mysql_db
        networks:
            - prismadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "Qwer!234"

    proxy:
        image: aprismatic/prismadb-proxy-mysql-trial:alpine
        container_name: prismadb_mysql_proxy
        networks:
            - prismadb
        ports:
            - 4000:4000
        depends_on:
            - db
        environment:
            ListenPort: "4000"
            ServerAddress: "db"
            ServerPort: "3306"
            Database: "testdb"

networks:
    prismadb: