version: '3.7'
services:

    db:
        image: aprismatic/mssql-server-linux-fulltext:latest
        container_name: prismadb_mssql_db
        deploy:
            restart_policy:
                condition: any
        networks:
            - prismadb
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "Qwer!234"
            ACCEPT_EULA: "Y"

    proxy:
        image: aprismatic.azurecr.io/prismadb-proxy-mssql:alpine
        container_name: prismadb_mssql_proxy
        deploy:
            restart_policy:
                condition: any
        volumes:
            - ${PWD}/dbsettings.json:/dbsettings.json
        networks:
            - prismadb
        ports:
            - 4000:4000
        depends_on:
            - db
        environment:
            ListenPort: "4000"
            DataSource: "db"
            InitialCatalog: "testdb"
            AdminUserId: "sa"
            DatabaseSettings: /dbsettings.json

networks:
    prismadb: